[build]
<<<<<<< HEAD
  base = "frontend"   # Directory containing package.json
  publish = "frontend/build"   # Directory where build output is located
  command = "npm run build"   # Command to build the project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
=======

  publish = "build"

  command = "npm run build"

[[redirects]]

  from = "/*"
  to = "/index.html"
  status = 200

>>>>>>> 9f14f6f1ea84c5d93c3d91f084646d29fa44c56c
